MotoHub/MotoHub/MotoHub/Models/Photo.cs
namespace MotoHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Photo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Photo()
        {
            Clubs = new HashSet<Club>();
            Events = new HashSet<Event>();
            UserProfiles = new HashSet<UserProfile>();
        }

        public int PhotoID { get; set; }

        public int PhotoAlbumID { get; set; }

        [Required]
        [StringLength(32)]
        public string PhotoName { get; set; }

        [Required]
        [StringLength(64)]
        public string ContentType { get; set; }

        [Column(TypeName = "image")]
        [Required]
        public byte[] PhotoData { get; set; }

        [StringLength(128)]
        public string PhotoCaption { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Club> Clubs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }

        public virtual PhotoAlbum PhotoAlbum { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}

MotoHub/MotoHub/MotoHub/Models/ViewModels/PhotosViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MotoHub.Models.ViewModels
{
    public class PhotosViewModel
    {
        public IEnumerable<Club> Clubs { get; set; }
        public IEnumerable<UserProfile> UserProfiles { get; set; }
        public IEnumerable<Event> Events { get; set; }
        public IEnumerable<Photo> Photos { get; set; }
    }
}

MotoHub/MotoHub/MotoHub/Controllers/PhotoController.cs
using MotoHub.DAL;
using MotoHub.Models;
using MotoHub.Models.ViewModels;
using System.Data.Entity;
using System;
using System.Linq;
using System.Web;
using MotoHub.MotoHubDevLibrary;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using MotoHub.Repositories.RepositoryInterfaces;

namespace MotoHub.Controllers
{
    public class PhotoController : Controller
    {
        private MotoHubDbContext db = new MotoHubDbContext();
        private DevTools devTools = new DevTools();
        private IPhotosRepository _photos;

        public PhotoController(IPhotosRepository photoRepo)
        {
            _photos = photoRepo;
        }

        public ActionResult EditPhotos(int? galleryID)
        {
            PhotoAlbumViewModel model = CreatePhotoAlbumViewModel(galleryID);

            return View(model);
        }

        public ActionResult GetPhotoEditPage(int? galleryID)
        {
            if(galleryID == null || galleryID <= 0)
            {
                throw new HttpException("The gallery you are looking for does not exist. HttpRequest galleryID is null or 0.");

            }
            else
            {
                return RedirectToAction("EditPhotos", new { galleryID });
            }
        }

        /// <summary>
        /// Create a PhotoAlbumViewModel based on a certian gallery.
        /// </summary>
        /// <param name="galleryID">Gallery to relate all PhotoAlbumViewModel models to.</param>
        /// <returns>PhotoAlbumViewModel</returns>
        private PhotoAlbumViewModel CreatePhotoAlbumViewModel(int? galleryID)
        {

            PhotoAlbumViewModel photoAlbumViewModel = new PhotoAlbumViewModel
            {
                Gallery = db.Galleries.Find(galleryID),
                PhotoAlbums = GetGalleryPhotoAlbums(galleryID),
                Photos = GetGalleryPhotos(galleryID)
            };

            return photoAlbumViewModel;
        }

        /// <summary>
        /// Return all of the PhotoAlbums associated with a particular gallery table entry.
        /// </summary>
        /// <param name="galleryID">The gallery to search in.</param>
        /// <returns>IEnmumerable<PhotoAlbums> list of PhotoAlbums</returns>
        private IEnumerable<PhotoAlbum> GetGalleryPhotoAlbums(int? galleryID)
        {
            List<PhotoAlbum> photoAlbums = db.PhotoAlbums.Where(pa => pa.GalleryID == galleryID).ToList();

            return photoAlbums;
        }

        /// <summary>
        /// Returns all of the Photos associated with a particular gallery table entry.
        /// </summary>
        /// <param name="galleryID">The gallery to search in.</param>
        /// <returns>IEnmumerable<Photo> list of Photos</returns>
        private IEnumerable<Photo> GetGalleryPhotos(int? galleryID)
        {
            List<Photo> photos = db.Photos.Where(p => p.PhotoAlbumID == db.PhotoAlbums
                                          .Where(pa => pa.GalleryID == galleryID)
                                          .Select(pa => pa.PhotoAlbumID)
                                          .FirstOrDefault())
                                          .ToList();
            return photos;
        }

        /// <summary>
        /// Returns a gallery with the matching galleryID input into the method.
        /// </summary>
        /// <param name="galleryID">Gallery to search for</param>
        /// <returns>A gallery table object</returns>
        private Gallery GetGallery(int? galleryID)
        {
            Gallery gallery = db.Galleries.Find(galleryID);

            return gallery;
        }

        /// <summary>
        /// Processes a request from the client to add a photo to a specified Photo Album.
        /// This will create the new Photo entry and update the database.
        /// </summary>
        /// <returns>Json result of success or failure.</returns>
        [HttpPost]
        public JsonResult AddPhotoToAlbum()
        {

            if(Request.Files.Keys.Count > 0)
            {
                //Get all of the keys from the HttpRequest.
                var keys = Request.Form.AllKeys;
                //Get string representation of AlbumID
                var stringAlbumID = Request.Form.Get(keys[0]);
                //Convert to int.
                Int32.TryParse(stringAlbumID, out int albumID);

                //Get a collection of all the files in the HttpRequest
                HttpFileCollectionBase fileCollection = Request.Files;
                //Get the file that is stored away.
                HttpPostedFileBase file = fileCollection[0];

                Photo newPhoto = new Photo
                {
                    PhotoName = file.FileName,
                    ContentType = file.ContentType,
                    PhotoData = new byte[file.ContentLength],
                    PhotoAlbumID = albumID,
                };
                //Create the byte stream of the photo.
                file.InputStream.Read(newPhoto.PhotoData, 0, file.ContentLength);

                db.Photos.Add(newPhoto);
                db.SaveChanges();

                return Json("Successfully Uploaded File");
            }
            else
            {
                return Json("No Files Selected.");
            }

        }

        public FileContentResult GetPhotoAsFile(int photoID)
        {
            Photo image = GetPhoto(photoID);

            return File(image.PhotoData, image.ContentType);
        }

        /// <summary>
        /// Gets the file of a photo based on the passed ID.
        /// </summary>
        /// <param name="photoID">ID of photo to return.</param>
        /// <returns>File format of the photo.</returns>
        public Photo GetPhoto(int photoID)
        {
            Photo image = db.Photos.Find(photoID);

            return image;
        }

        public JsonResult Edit([Bind(Prefix = "item")]Photo photo)
        {

            Photo photoToUpdate = db.Photos.Find(photo.PhotoID);

            photoToUpdate.PhotoCaption = photo.PhotoCaption;

            db.Entry(photoToUpdate).State = EntityState.Modified;
            db.SaveChanges();

            return Json("Edited");
        }

        [Authorize]
        public ActionResult DeletePhoto(int photoID)
        {
            //Check to see if this photo is a profile photo somewhere before removing it.
            Photo photoToRemove = db.Photos.Find(photoID);
            UserProfile profile = db.UserProfiles.Where(up => up.ProfilePhotoID == photoID).FirstOrDefault();
            Event @event = db.Events.Where(e => e.ProfilePhotoID == photoID).FirstOrDefault();
            Club club = db.Clubs.Where(c => c.ProfilePhotoID == photoID).FirstOrDefault();
            int galleryID = photoToRemove.PhotoAlbum.GalleryID;

            if(profile != null)
            {
                profile.ProfilePhotoID = null;
                profile.Photo = null;
                db.Entry(profile).State = EntityState.Modified;
                db.SaveChanges();
            }
            else if(@event != null)
            {
                @event.ProfilePhotoID = null;
                @event.Photo = null;
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
            }
            else if (club != null)
            {
                club.ProfilePhotoID = null;
                club.Photo = null;
                db.Entry(club).State = EntityState.Modified;
                db.SaveChanges();
            }

            db.Photos.Remove(photoToRemove);
            db.SaveChanges();

            return RedirectToAction("EditPhotos", new { galleryID });
        }

        /// <summary>
        /// This will determine, based on the passed in galleryID, what table should be updated with a new photoID for
        /// it's ProfilePhotoID row.
        /// </summary>
        /// <param name="galleryID">The gallery the update should happen in.</param>
        /// <param name="photoID">The photo that will become the new profile photo.</param>
        /// <returns>View of the EditPhotos page.</returns>
        public ActionResult SetProfilePhoto(int? galleryID, int? photoID)
        {
            if(galleryID == null || galleryID <= 0)
            {
                throw new HttpException("The gallery recieved from the HttpRequest is either null or 0.");
            }
            else if(photoID == null || photoID <= 0)
            {
                throw new HttpException("The photo recieved from the HttpRequest is either null or 0.");
            }
            else
            {
                Gallery galleryFound = GetGallery(galleryID);

                if(galleryFound.UserProfiles.Count() > 0)
                {
                    AssignUserProfilePhoto(photoID, galleryFound.UserProfiles.Select(up => up.MotoHubUserID).FirstOrDefault());
                }
                else if(galleryFound.Clubs.Count() > 0)
                {
                    AssignClubProfilePhoto(photoID, galleryFound.Clubs.Select(c => c.ClubsID).FirstOrDefault());
                }
                else if(galleryFound.Events.Count() > 0)
                {
                    AssignEventProfilePhoto(photoID, galleryFound.Events.Select(e => e.EventsID).FirstOrDefault());
                }
                else
                {
                    throw new Exception("This gallery is an orphan. No Clubs, no UserProfile and no Events are associated with this Gallery.");
                };

                return RedirectToAction("EditPhotos", new { galleryID }); 
            }

        }

        /// <summary>
        /// Assigns a new ProfilePhotoID to the user.
        /// </summary>
        /// <param name="photoID">PhotoID of the new profile photo.</param>
        /// <param name="userID">MotoHubUserID of the user to update.</param>
        public void AssignUserProfilePhoto(int? photoID, int? userID)
        {
            if(photoID == null || photoID <= 0)

MotoHub/MotoHub/MotoHub/Views/Photo/EditPhotos.cshtml
@model MotoHub.Models.ViewModels.PhotoAlbumViewModel

@{
    ViewBag.Title = "EditPhoto";
}

<link href="~/Content/photos-upload.css" rel="stylesheet" type="text/css" />

<h2>@Model.PhotoAlbums.Select(pa => pa.PhotoAlbumName).FirstOrDefault() Album</h2>

<button id="upload-photo-button" class="btn btn-info btn-xs">upload photo</button>

<div id="drop-box-container">
    <div id="drop-box">
        <form class="drop-box-form" enctype="multipart/form-data" data-album-value="@Model.PhotoAlbums.Select(pa=> pa.PhotoAlbumID).FirstOrDefault()" id="form">
            <p>Drop Here</p>
            <input type="file" id="file-element" onchange="handleFiles(this.files)" name="inputFile" />
            <label class="button" for="file-element">Select some files</label>
        </form>
    </div>
</div>
<br />

<div id="photo-container">
    @{ int i = 0; }
    @if (Model.Photos.Count() > 0)
    {
        <div class="row">
            @foreach (var item in Model.Photos)
            {
                i++;
                <div class="@(i%4 == 0 ? "row" : "")">
                    <div class="col-sm-3">
                        <div class="panel panel-default">
                        
                            <div class="panel-heading">
                                <div class="dropdown">
                                    <a class="btn btn-default btn-xs" data-toggle="dropdown">
                                        <span class="glyphicon glyphicon-align-center"></span>
                                    </a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li role="presentation"><a role="menuitem" href="#" onclick="showEditPane(event, @item.PhotoID)">Edit</a></li>
                                        <li role="presentation">@Html.ActionLink("Delete", "DeletePhoto", "Photo", new { photoID = item.PhotoID }, new { @role = "menuitem" })</li>
                                        <li role="presentation">@Html.ActionLink("Set As Profile Photo", "SetProfilePhoto", "Photo", new { photoID = item.PhotoID, galleryID = Model.Gallery.GalleryID }, new { @role = "menuitem" })</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="panel-body">
                                <a href="#" class="thumbnail">
                                    <img src='@Url.Action("GetPhotoAsFile", "Photo", new { photoID = item.PhotoID})' />
                                </a>
                            </div>

                            <div class="panel-footer">
                                <p>
                                    @item.PhotoCaption
                                </p>
                                <div id="edit-pane-@item.PhotoID" class="edit-pane">
                                    @using (Ajax.BeginForm("Edit", "Photo", new AjaxOptions { HttpMethod = "POST", OnSuccess = "reloadPhotoContainer()"}, new { photo = item }))
                                    {
                                        @Html.HiddenFor(modelItem => item.PhotoAlbumID)
                                        @Html.HiddenFor(modelItem => item.PhotoData)
                                        @Html.HiddenFor(modelItem => item.PhotoID)
                                        @Html.HiddenFor(modelItem => item.PhotoName)
                                        @Html.HiddenFor(modelItem => item.ContentType)

                                        @Html.EditorFor(modelItem => item.PhotoCaption, new { htmlAttributes = new { @Value = "" } })

                                        <input type="submit" value="Save" class="btn" />
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    }
    else
    {
        <p>No Images Availible</p>
    }
            
</div>

@section Scripts {
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/photo-upload.js"></script>
}