MotoHub/MotoHub/MotoHub/Models/Event.cs
namespace MotoHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            Registrations = new HashSet<Registration>();
        }

        [Key]
        public int EventsID { get; set; }

        public int MotoHubUserID { get; set; }

        public int ClubID { get; set; }

        [Required]
        [StringLength(64)]
        [Display(Name="Event Name")]
        public string EventName { get; set; }

        [Required]
        [Column(TypeName = "date")]
        [Display(Name="Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString="{0:dd/MM/yyyy}")]
        [DateIsInFuture(ErrorMessage = "Ok...so... we are gonna learn about dates today. \nDates must be in the format Day/Month/Year. \nWhen creating your event, you will also need to make sure the date for the event hasn't already passed. \nSo... yeah...Got it now?")]
        public DateTime EventDate { get; set; }

        [Required]
        [StringLength(64)]
        [Display(Name="Street")]
        public string EventLocationStreet { get; set; }

        [Required]
        [StringLength(64)]
        [Display(Name="City")]
        public string EventLocationCity { get; set; }

        [Required]
        [StringLength(64)]
        [Display(Name="State")]
        public string EventLocationState { get; set; }

        [Display(Name="Zip")]
        public int EventLocationZip { get; set; }

        public int? ProfilePhotoID { get; set; }

        public int GalleryID { get; set; }

        public virtual Club Club { get; set; }

        public virtual Gallery Gallery { get; set; }

        public virtual MotoHubUser MotoHubUser { get; set; }

        public virtual Photo Photo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registrations { get; set; }

        [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false)]
        public class DateIsInFuture : ValidationAttribute
        {
            public override bool IsValid(object date)
            {
                if(date != null)
                {
                    DateTime returnDate = (DateTime)date;
                    return returnDate > DateTime.Now;
                }
                else
                {
                    return false;
                }
            }
        }
    }
}

MotoHub/MotoHub/MotoHub/Models/EventResult.cs
namespace MotoHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class EventResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventResult()
        {
            RunDatas = new HashSet<RunData>();
        }

        [Key]
        public int EventResultsID { get; set; }

        public int RegistrationID { get; set; }

        public string RunGroupCode { get; set; }

        public string RunSectionCode { get; set; }

        [Required]
        public int CarClassID { get; set; }

        public TimeSpan? BestTime { get; set; }

        public int? Points { get; set; }

        public virtual Registration Registration { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RunData> RunDatas { get; set; }
    }
}

MotoHub/MotoHub/MotoHub/Models/ViewModels/EventResultsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MotoHub.Models.ViewModels
{
    public class EventResultsViewModel
    {
        public IEnumerable<EventResult> EventResults { get; set; }
        public IEnumerable<RunData> RunData { get; set; }
        public IEnumerable<RunGroup> RunGroup { get; set; }
        public IEnumerable<RunSection> RunSection { get; set; }
    }
}

MotoHub/MotoHub/MotoHub/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MotoHub.DAL;
using MotoHub.Models;
using MotoHub.MotoHubDevLibrary;
using GuigleAPI;
using GuigleAPI.Model;
using Microsoft.AspNet.Identity;
using MotoHub.Models.ViewModels;
using MotoHub.Repositories.Persistance;
using MotoHub.Repositories.RepositoryInterfaces;
using MotoHub.Repositories;

namespace MotoHub.Controllers
{
    public class EventsController : Controller
    {
        private MotoHubDbContext db = new MotoHubDbContext();
        private DevTools devTools = new DevTools();
        private UnitOfWork unitOfWork = new UnitOfWork(new MotoHubDbContext());
        private IEventRepository _events;
        private IClubRepository _clubs;
        private IMembershipRepository _memberships;
        private IRoleRepository _roles;
        private IMotoHubUserRepository _motoHubUsers;
        private IRunDataRepository _runDatas;
        private IEventResultsRepository _eventResults;
        private IRegistrationRepository _registrations;
        private IGalleriesRepository _galleries;
        private IPhotoAlbumsRepository _photoAlbums;
        private IPhotosRepository _photos;
        private IGarageRepository _garage;
        private IRunGroupRepository _runGroup;
        private IRunSectionRepository _runSection;

        /// <summary>
        /// Constructor for all repositories to be accessed on the live site.
        /// </summary>
        /// <param name="eventRepository"></param>
        /// <param name="clubRepo"></param>
        /// <param name="memRepo"></param>
        /// <param name="roleRepository"></param>
        /// <param name="userRepo"></param>
        /// <param name="runDataRepo"></param>
        public EventsController(IEventRepository eventRepository, IClubRepository clubRepo, IMembershipRepository memRepo, IRoleRepository roleRepository, IMotoHubUserRepository userRepo, IRunDataRepository runDataRepo, IEventResultsRepository eventResultsRepo, IRegistrationRepository registrationRepo, IGalleriesRepository galleriesRepo, IPhotoAlbumsRepository photoAlbumsRepo, IPhotosRepository photosRepo, IGarageRepository garageRepo, IRunGroupRepository runGroupRepo, IRunSectionRepository runSectionRepo)
        {
            _events = eventRepository;
            _clubs = clubRepo;
            _memberships = memRepo;
            _roles = roleRepository;
            _motoHubUsers = userRepo;
            _runDatas = runDataRepo;
            _eventResults = eventResultsRepo;
            _registrations = registrationRepo;
            _galleries = galleriesRepo;
            _photoAlbums = photoAlbumsRepo;
            _photos = photosRepo;
            _garage = garageRepo;
            _runGroup = runGroupRepo;
            _runSection = runSectionRepo;
        }

        /// <summary>
        /// Constuctor for specific repos pertaining to Moq testings.
        /// </summary>
        /// <param name="mockClubRepo"></param>
        /// <param name="mockEventRepo"></param>
        /// <param name="mockUserRepo"></param>
        /// <param name="mockMembershipRepo"></param>
        /// <param name="mockRoleRepo"></param>
        public EventsController(IClubRepository mockClubRepo, IEventRepository mockEventRepo, IMotoHubUserRepository mockUserRepo, IMembershipRepository mockMembershipRepo, IRoleRepository mockRoleRepo)
        {
            _events = mockEventRepo;
            _clubs = mockClubRepo;
            _memberships = mockMembershipRepo;
            _roles = mockRoleRepo;
            _motoHubUsers = mockUserRepo;
        }

        public bool MoqCreatedSuccessfully()
        {
            if (this._events.GetAll().Count() <= 0)
            {
                return false;
            }
            else
            {
                return true;
            }

        }

        public ActionResult EventResults(int eventID)
        {
            return View(_events.Get(eventID));
        }

        public ActionResult EditEventResults(int runDataID, int eventResultsID)
        {
            IEnumerable<RunData> runDataToEdit = _runDatas.GetAll().Where(rd => rd.RunDataID == runDataID);
            IEnumerable<EventResult> eventResultToEdit = _eventResults.GetAll().Where(er => er.EventResultsID == eventResultsID);

            EventResultsViewModel eventResultsViewModel = CreateEventResultsViewModel(eventResultToEdit, runDataToEdit);

            return View(eventResultsViewModel);
        }

        [HttpPost]
        public ActionResult EditEventResults([Bind(Prefix = "eventResultItem")] EventResult eventResult, [Bind(Prefix = "runDataItem")] RunData runData)
        {
            EventResult eventResultToEdit = _eventResults.Get(eventResult.EventResultsID);
            RunData runDataToEdit = _runDatas.Get(runData.RunDataID);

            eventResultToEdit.Points = eventResult.Points;
            eventResultToEdit.RunGroupCode = eventResult.RunGroupCode;
            eventResult.RunSectionCode = eventResult.RunSectionCode;

            runDataToEdit.RawTime = runData.RawTime;
            runDataToEdit.AdjustedTime = runData.AdjustedTime;
            runDataToEdit.Finished = runData.Finished;
            runDataToEdit.RunNumber = runData.RunNumber;
            runDataToEdit.Penalty = runData.Penalty;

            _runDatas.SetModified(runDataToEdit);
            _eventResults.SetModified(eventResultToEdit);

            _eventResults.SaveChanges();
            _runDatas.SaveChanges();

            EventResult test = _eventResults.Get(eventResult.EventResultsID);
            return RedirectToAction("EventResults", new { eventID = eventResultToEdit.Registration.EventID });
        }

        /// <summary>
        /// Gets all of the EventResult table entries associated with an event.
        /// </summary>
        /// <param name="eventID">Event to look in.</param>
        /// <returns>List of EventResults table entries.</returns>
        private IEnumerable<EventResult> GetAllEventResults(int eventID)
        {
            return _eventResults.GetAll().Where(er => er.Registration.EventID == eventID).ToList();
        }

        /// <summary>
        /// Gets all of the RunData tables that are associated with each of the EventResults tables in
        /// the IEnumerable list passed in.
        /// </summary>
        /// <param name="eventResults">IEnumerable of EventResult tables to be looked at.</param>
        /// <returns>IEnumerable of RunData</returns>
        private IEnumerable<RunData> GetAllRunDataFromEventResults(IEnumerable<EventResult> eventResults)
        {
            IEnumerable<RunData> runDataFromEventResults = new List<RunData>();

            foreach (var item in eventResults)
            {
                runDataFromEventResults = runDataFromEventResults.Concat(item.RunDatas);
            }

            return runDataFromEventResults;
        }

        private IEnumerable<EventResult> GetAllUserEventResults(int userID)
        {
            return _eventResults.GetAll().Where(er => er.Registration.UserID == userID).ToList();
        }

        public PartialViewResult GetAllUserPastEventResults()
        {
            int userID = _motoHubUsers.GetCurrentUser(User.Identity.GetUserId()).MotoHubUserID;

            IEnumerable<EventResult> allUserEventResults = GetAllUserEventResults(userID);

            List<EventResult> pastEventResults = GetAllPastEventResults(allUserEventResults);

            IEnumerable<RunData> allUserRunDataFromPastEventResults = GetAllRunDataFromEventResults(pastEventResults);

            EventResultsViewModel pastEventResultsViewModel = CreateEventResultsViewModel(pastEventResults, allUserRunDataFromPastEventResults);

            return PartialView("_UserEventResultsPartialView", pastEventResultsViewModel);
        }

        /// <summary>
        /// Gets all of the EventResults for the current user within the specified time range given.
        /// </summary>
        /// <param name="startDate">Start of the time range.</param>
        /// <param name="endDate">End of the time range.</param>
        /// <returns>Partial View of a table containing the results.</returns>
        public PartialViewResult GetUserEventResultsInDateRange(DateTime startDate, DateTime endDate)
        {
            int userID = _motoHubUsers.GetCurrentUser(User.Identity.GetUserId()).MotoHubUserID;

            IEnumerable<EventResult> allUserEventResults = GetAllUserEventResults(userID);
            List<EventResult> pastEventResults = new List<EventResult>();

            foreach (var eventResult in allUserEventResults)
            {
                if (eventResult.Registration.Event.EventDate < endDate && eventResult.Registration.Event.EventDate > startDate)
                {
                    pastEventResults.Add(eventResult);
                }
            }

            IEnumerable<RunData> allUserRunDataFromPastEventResults = GetAllRunDataFromEventResults(pastEventResults);

            EventResultsViewModel pastEventResultsViewModel = CreateEventResultsViewModel(pastEventResults, allUserRunDataFromPastEventResults);

            return PartialView("_UserEventResultsPartialView", pastEventResultsViewModel);
        }

        /// <summary>
        /// Gets the most recent 
        /// </summary>
        /// <param name="numberOfResults"></param>
        /// <returns></returns>
        public PartialViewResult GetSpecifiedNumberOfMostRecentUserEventResults(int numberOfResults)
        {
            int userID = _motoHubUsers.GetCurrentUser(User.Identity.GetUserId()).MotoHubUserID;

            IEnumerable<EventResult> allUserEventResults = GetAllUserEventResults(userID);

            List<EventResult> pastEventResults = GetAllPastEventResults(allUserEventResults);

MotoHub/MotoHub/MotoHub/Views/Events/Address.cshtml
@{
    ViewBag.Title = "Address";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Address</h2>

MotoHub/MotoHub/MotoHub/Views/Events/Create.cshtml
@model MotoHub.Models.Event

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Event</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
    @Html.HiddenFor(model => model.MotoHubUserID)
    @Html.HiddenFor(model => model.ClubID)

    <div class="form-group">
        @Html.LabelFor(model => model.EventName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventLocationStreet, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventLocationStreet, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventLocationStreet, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventLocationCity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventLocationCity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventLocationCity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventLocationState, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventLocationState, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventLocationState, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventLocationZip, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventLocationZip, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventLocationZip, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MotoHub/MotoHub/MotoHub/Views/Events/EditEventResults.cshtml
@model MotoHub.Models.ViewModels.EventResultsViewModel

@{
    List<SelectListItem> groupSection = new List<SelectListItem>();
    List<SelectListItem> runSection = new List<SelectListItem>();

    runSection.Add(new SelectListItem
    {
        Text = "Time",
        Value = "Time"
    });

    runSection.Add(new SelectListItem
    {
        Text = "AM",
        Value = "AM"
    });
    runSection.Add(new SelectListItem
    {
        Text = "PM",
        Value = "PM"
    });
    groupSection.Add(new SelectListItem
    {
        Text = "Group",
        Value = "Group"
    });
    groupSection.Add(new SelectListItem
    {
        Text = "Group 1",
        Value = "G1"
    });
    groupSection.Add(new SelectListItem
    {
        Text = "Group 2",
        Value = "G2"
    });
}

<link rel="stylesheet" href="~/Content/animsition.min.css" />
<div class="animsition">
    @{
        ViewBag.Title = "Update Event Results ";
    }

    <h2>Update Event Results</h2>
    <table id="runResultsEditTable" class="table table-hover table-responsive table-bordered">
        <thead>
            <tr class="col-md-12">
                <th>
                    <p>Run Number</p>
                </th>
                <th>
                    <p>Competitor Name</p>
                </th>
                <th>
                    <p>Competitor Club</p>
                </th>
                <th>
                    <p>Run Group</p>
                </th>
                <th>
                    <p>Run Section</p>
                </th>
                <th>
                    <p>Raw Time</p>
                </th>
                <th>
                    <p>Adjusted Time</p>
                </th>
                <th>
                    <p>Penalty</p>
                </th>
                <th>
                    <p>Finished</p>
                </th>
                <th>
                    <p>Points</p>
                </th>
                <th>
                    <p>Best Time</p>
                </th>
            </tr>
        </thead>
        <tbody>

            @foreach (var eventResultItem in Model.EventResults)
            {
                foreach (var runDataItem in Model.RunData)
                {
                    using (Html.BeginForm("EditEventResults", "Events", new {eventResults = eventResultItem, runData = runDataItem }, FormMethod.Post, null))
                    {
                        @Html.HiddenFor(model => eventResultItem.EventResultsID);
                        @Html.HiddenFor(model => eventResultItem.RegistrationID);
                        @Html.HiddenFor(model => eventResultItem.CarClassID);
                        @Html.HiddenFor(model => runDataItem.EventResultsID);
                        @Html.HiddenFor(model => runDataItem.RunDataID);
                        @Html.HiddenFor(model => eventResultItem.BestTime);
                        @Html.HiddenFor(model => model.RunGroup);
                        @Html.HiddenFor(model => model.RunSection);
                        <tr id="event-results-edit" class="col-md-12 form-group">
                            <td>
                                @Html.EditorFor(model => runDataItem.RunNumber, new { htmlAttributes = new { @class = "form-control" } })
                            </td>
                            <td>
                                @Html.DisplayFor(model => eventResultItem.Registration.MotoHubUser.UserProfile.FirstName, new { htmlAttributes = new { @class = "form-control" } }) @Html.DisplayFor(model => eventResultItem.Registration.MotoHubUser.UserProfile.LastName, new { htmlAttributes = new { @class = "form-control" } })
                            </td>
                            <td>
                                @Html.DisplayFor(model => eventResultItem.Registration.Club.ClubName, new { htmlAttributes = new { @class = "form-control" } })
                            </td>
                            <td class="col-md-1">
                                @Html.DropDownListFor(model => eventResultItem.RunGroupCode, new SelectList(Model.RunGroup, "RunGroupCode", "RunGroupCode"), new { @class = "form-control" })
                            </td>
                            <td class="col-md-1">
                                @Html.DropDownListFor(model => eventResultItem.RunSectionCode, new SelectList(Model.RunSection, "RunSectionCode", "RunSectionCode"), new { @class = "form-control" })
                            </td>
                            <td>
                                @Html.TextBoxFor(model => runDataItem.RawTime, "{0:hh\\:mm\\:ss\\.ff}",new { @class = "form-control" })
                                <p><small>Format: hours:minutes:seconds.tenths</small></p>
                            </td>
                            <td>
                                @Html.TextBoxFor(model => runDataItem.AdjustedTime, "{0:hh\\:mm\\:ss\\.ff}", new { @class = "form-control" })
                                <p><small>Format: hours:minutes:seconds.tenths</small></p>
                            </td>
                            <td>
                                @Html.EditorFor(model => runDataItem.Penalty, new { htmlAttributes = new { @class = "form-control" } })
                            </td>
                            <td>
                                @Html.EditorFor(model => runDataItem.Finished, new { htmlAttributes = new { @class = "form-control" } })
                            </td>
                            <td>
                                @Html.EditorFor(model => eventResultItem.Points, new { htmlAttributes = new { @class = "form-control" } })
                            </td>
                            <td>
                                @Html.DisplayFor(model => eventResultItem.BestTime, new { htmlAttributes = new { @class = "form-control" } })
                            </td>
                            <td>
                                <button type="submit" class="btn btn-info btn-xs">Save</button>
                            </td>
                        </tr>
                    }
                }
            }
        </tbody>
    </table>
</div>
@section scripts {
    <script src="~/Scripts/eventresults.js" type="text/javascript">
    </script>
    <script src="~/Scripts/animsition.min.js"></script>
}

MotoHub/MotoHub/MotoHub/Views/Events/EventOver.cshtml
@{
    ViewBag.Title = "EventOver";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Event Over</h2>

<div class="jumbotron">
    Past events cannot be edited.
    @Html.ActionLink("Back to previous page", null, null, null, new { href = Request.UrlReferrer })
</div>

MotoHub/MotoHub/MotoHub/Views/Events/EventResults.cshtml
@model MotoHub.Models.Event
@{
    ViewBag.Title = Model.EventName + "Event Results";
}

<link rel="stylesheet" href="~/Content/animsition.min.css" />
<div class="animsition" data-animsition-in-class="fade-in-right" , data-animsition-out-class="fade-out-right">
    <h2>@Model.EventName Event Results</h2>


    <div class="row">
        <div class="col-sm-3">
            <select id="run-group-dropdown" name="run-group-dropdown" class="form-control">
                <option>Select Run Group</option>
                <option value="AM">AM</option>
                <option value="PM">PM</option>
            </select>
        </div>
        <div class="col-sm-6">
            <select id="run-section-dropdown" name="run-section-dropdown" class="form-control">
                <option>Select Run Section</option>
                <option value="G1">G1</option>
                <option value="G2">G2</option>
            </select>

            <br />
            <input class="btn btn-info btn-sm" type="submit" value="Filter" onclick="filterResults(@Model.EventsID)" />
            <input class="btn btn-info btn-sm" type="button" value="Remove Filters" onclick="window.location.href=window.location.href" />

            @Html.ActionLink("Back to Admin Dashboard", "ClubAdminDashboard", "Clubs", new { clubID = Model.ClubID }, new { @class = "animsition-link" })

        </div>
    </div>
    <hr />
    <div id="eventResultsTableContainer" class="row">
        @{Html.RenderAction("GetEventResultsTablePartialView", "Events", new { eventID = Model.EventsID });}
    </div>
</div>
    @section scripts {
        <script src="~/Scripts/eventresults.js" type="text/javascript">
        </script>
        <script src="~/Scripts/animsition.min.js"></script>
    }

MotoHub/MotoHub/MotoHub/Views/Events/_AdminDetails.cshtml
@model MotoHub.Models.ViewModels.EventAdminEditViewModel
@Html.ActionLink("Edit", "Edit", "Events", new { id = Model.Event.EventsID }, new { @class = "btn btn-info btn-xs" })

MotoHub/MotoHub/MotoHub/Views/Events/_EventResultsTable.cshtml
@model MotoHub.Models.ViewModels.EventResultsViewModel

<div>
    <table id="runResultsTable" class="table table-hover table-responsive table-bordered">
        <thead>
            <tr class="col-md-12">
                <th>
                    <p>Run Number</p>
                </th>
                <th>
                    <p>Competitor Name</p>
                </th>
                <th>
                    <p>Competitor Club</p>
                </th>
                <th>
                    <p>Run Group</p>
                </th>
                <th>
                    <p>Run Section</p>
                </th>
                <th>
                    <p>Raw Time</p>
                </th>
                <th>
                    <p>Adjusted Time</p>
                </th>
                <th>
                    <p>Penalty</p>
                </th>
                <th>
                    <p>Finished</p>
                </th>
                <th>
                    <p>Points</p>
                </th>
                <th>
                    <p>Best Time</p>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var eventResultItem in Model.EventResults)
            {
                foreach (var runDataItem in Model.RunData.Where(rd => rd.EventResultsID == eventResultItem.EventResultsID))
                {
                    <tr id="event-results-read-only" class="col-md-12">
                        <td>
                            @Html.DisplayFor(model => runDataItem.RunNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(model => eventResultItem.Registration.MotoHubUser.UserProfile.FirstName) @Html.DisplayFor(model => eventResultItem.Registration.MotoHubUser.UserProfile.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(model => eventResultItem.Registration.Club.ClubName)
                        </td>
                        <td>
                            @Html.DisplayFor(model => eventResultItem.RunGroupCode)
                        </td>
                        <td>
                            @Html.DisplayFor(model => eventResultItem.RunSectionCode)
                        </td>

                        <td>
                            @if (runDataItem.RawTime != null)
                            {
                                @Html.DisplayFor(model => runDataItem.RawTime.Value)
                            }
                            else
                            {
                                @Html.Label("00");
                            }

                        </td>
                        <td>
                            @if (runDataItem.AdjustedTime != null)
                            {
                                @Html.DisplayFor(model => runDataItem.AdjustedTime.Value)
                            }
                            else
                            {
                                @Html.Label("00");
                            }
                        </td>
                        <td>
                            @Html.DisplayFor(model => runDataItem.Penalty)
                        </td>
                        <td>
                            @Html.DisplayFor(model => runDataItem.Finished)
                        </td>
                        <td>
                            @Html.DisplayFor(model => eventResultItem.Points)
                        </td>
                        <td>
                            @Html.DisplayFor(model => eventResultItem.BestTime)
                        </td>
                        <td>
                            <div class="dropdown">
                                <a class="btn btn-default btn-xs" data-toggle="dropdown">
                                    <span class="glyphicon glyphicon-align-center"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li role="presentation" onclick="showResultsEdit()">@Html.ActionLink("Update Entry", "EditEventResults", "Events", routeValues: new { runDataID = runDataItem.RunDataID, eventResultsID = eventResultItem.EventResultsID }, htmlAttributes: new { @role = "menuitem", @class = "animsition-link" })</li>
                                </ul>
                            </div>
                        </td>
                    </tr>

                }
            }
        </tbody>
    </table>
</div>

@section scripts{
    <script src="~/Scripts/animsition.min.js"></script>
}