MotoHub/MotoHub/MotoHub/Controllers/EventRegistrationController.cs
using Microsoft.AspNet.Identity;
using MotoHub.DAL;
using MotoHub.Models;
using MotoHub.Models.ViewModels;
using MotoHub.MotoHubDevLibrary;
using MotoHub.Repositories.Persistance;
using MotoHub.Repositories.RepositoryInterfaces;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;
using ZXing;
using ZXing.Common;
using ZXing.QrCode;

namespace MotoHub.Controllers
{
    public class EventRegistrationController : Controller
    {
        private IRegistrationRepository registrationRepository;
        MotoHubDbContext db = new MotoHubDbContext();
        DevTools devTools = new DevTools();
        UnitOfWork unitOfWork = new UnitOfWork(new MotoHubDbContext());

        public EventRegistrationController(IRegistrationRepository registrationRepository)
        {
            this.registrationRepository = registrationRepository;
        }

        [Authorize]
        public ActionResult ManageCreateNew(int? eventID)
        {
            int userID = devTools.GetCurrentUser(db, User.Identity.GetUserId()).MotoHubUserID;
            return RedirectToAction("CreateNew", new { id = eventID , userID });
        }

        [Authorize]
        [HttpGet]
        public ActionResult CreateNew(int? id , int? userID)
        {   
            
            Event @event = db.Events.Find(id);

            if (@event == null)
            {
                return HttpNotFound();
            }

            foreach (var item in db.Registrations)
            {
                int? regID = item.UserID;
                int? regEvent = item.EventID;

                if(@event.EventDate < DateTime.Now)
                {
                    System.Windows.Forms.MessageBox.Show("Event Is Already Over");
                    return RedirectToAction("Details/" + @event.EventsID, "Events");
                }

                if (regID == userID && regEvent == id)
                {
                    System.Windows.Forms.MessageBox.Show("You Are Already Registered For This Event");
                    return RedirectToAction("Details/" + @event.EventsID, "Events");
                }
            }
            RegistrationViewModel viewmodel = CreateRegViewModel(id, userID);

            return View(viewmodel);
        }


        [Authorize]
        [HttpPost]
        public ActionResult CreateNew(System.Web.Mvc.FormCollection form, int userID)
        {
            Registration reg = db.Registrations.Create();

            var FormEvent = form["Event"];
            var FormClub = form["Club"];
            var FormCar = form["Cars"];
            var FormCarClass = form["CarClass"];
            var FormRunGroup = form["RunGroup"];

            reg.UserID = userID;
            reg.EventID = db.Events.Where(m => m.EventName == FormEvent).Select(m => m.EventsID).FirstOrDefault();

            if(FormClub != "")
            {
                reg.ClubsID = db.Clubs.Where(m => m.ClubName == FormClub).Select(m => m.ClubsID).FirstOrDefault();
            }

            if(FormCar != "")
            {
                int carIDFound = Convert.ToInt32(FormCar);
                reg.CarID = db.Cars.Where(c => c.CarID == carIDFound).Select(c => c.CarID).FirstOrDefault();
            }

            if(FormCarClass != "" && FormRunGroup != "")
            {
                int carClassID = unitOfWork.CarClasses.GetCarClassIDFromCarClassName(FormCarClass.ToString());

                if (ModelState.IsValid)
                {
                               
                    db.Registrations.Add(reg);
                    db.SaveChanges();

                    CreateNewEventResultsTableEntry(reg.EventID,reg.RegistrationID, carClassID, FormRunGroup.ToString());
                    return RedirectToAction("Index", "Events");
                }

            }

            return RedirectToAction("CreateNew", new { id = reg.EventID, userID });
        }

        private void CreateNewEventResultsTableEntry(int eventID, int registrationID, int carClassID, string runGroupCode)
        {
            string runSectionCode = GetRunSectionCodeForNewRegistration(eventID);
            
            EventResult newEventResultTable = unitOfWork.EventResults.Create(registrationID, carClassID, runGroupCode, runSectionCode);
            CreateFirstRunDataTableEntry(newEventResultTable.EventResultsID);
        }

        /// <summary>
        /// Determines how many registrations there are in the event and if there is an even number of registrations that have
        /// been created (and thus assined a run section) then they are assigned to Group 1, else they are assigned to Group 2.
        /// </summary>
        /// <param name="eventID">Event that is being registered for.</param>
        /// <returns>String. The runSectionCode.</returns>
        private string GetRunSectionCodeForNewRegistration(int eventID)
        {
            string runSectionCode;

            if(unitOfWork.Events.Get(eventID).Registrations.Count() > 0)
            {
                int numberOfRegistrations = unitOfWork.Events.Get(eventID).Registrations.Count();
                if(numberOfRegistrations % 2 == 0)
                {
                    runSectionCode = "G1";
                }
                else
                {
                    runSectionCode = "G2";
                }
            }
            else
            {
                runSectionCode = "G1";
            }

            return runSectionCode;
        }

        /// <summary>
        /// Creates the first entry in the rundata table for an event attendee.
        /// </summary>
        /// <param name="eventResultsID">EventResults table ID to link to.</param>
        private void CreateFirstRunDataTableEntry(int eventResultsID)
        {
            unitOfWork.RunData.Create(eventResultsID);
        }

        /// <summary>
        /// For creating a new RunData entry with a specified runNumber.
        /// </summary>
        /// <param name="runNumber">Run Number</param>
        /// <param name="eventResults">EventResults table ID to link to.</param>
        private void CreateNewRunDataTableEntry(int eventResults, int runNumber)
        {

        }

        [Authorize]
        public ActionResult RemoveRegistration(int registrationID)
        {
            Registration registrationToUpdate = db.Registrations.Find(registrationID);

            db.Registrations.Remove(registrationToUpdate);
            db.SaveChanges();

            return RedirectToAction("UserHome", "Profile");
        }

        /// <summary>
        /// Test for PBI 266
        /// </summary>
        /// <param name="registration"></param>
        /// <returns></returns>
        public bool CreatedSuccessfully(Registration registration)
        {
            if (registration.EventID == 0 && registration.UserID == 0)
            {
                throw new Exception("Registration was not created correctly.");
            }
            else
            {
                return true;
            }
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize]
        private RegistrationViewModel CreateRegViewModel(int? eventID, int? userID)
        {

            ViewBag.Event = eventID;
            RegistrationViewModel RVM = new RegistrationViewModel
            {
                Garage = db.Garages.Where(m => m.MotoHubUserID == userID).ToList(),

                Cars = db.Cars.Where(m => m.MotoHubUserID == userID).ToList(),

                Event = db.Events.Where(m => m.EventsID == eventID),

                Club = db.Clubs.Where(m => m.Memberships.Select(a => a.MotoHubUserID).FirstOrDefault() == userID).ToList(),

                Registration = db.Registrations.ToList(),

                UserProfile = db.UserProfiles.Where(m => m.MotoHubUserID == userID),

                CarMake = db.CarMakes.ToList(),

                CarClass = unitOfWork.CarClasses.GetAllCarClasses(),

                RunGroup = unitOfWork.RunGroups.GetAllRunGroups()
                
            };

            return RVM;
        }

        public ActionResult QRCodeScan()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetQRPartial(QRViewModel qr)
        {
            UnitOfWork unitOfWork = new UnitOfWork(db);


            if (qr.Type == "U")
            {
                int uid = Convert.ToInt32(qr.Id);
                MotoHubUser user = unitOfWork.MotoHubUsers.Get(uid);
                return PartialView("_QRUser", user);
            }
            else if (qr.Type == "C")
            {
                int cid = Convert.ToInt32(qr.Id);
                Car car = unitOfWork.Cars.Get(cid);
                return PartialView("_QRCar", car);
            }
            return PartialView("Error");
        }

        private bool CheckValidQRCode(QRViewModel qr)
        {
            bool typeResult = false;
            bool idResult = false;

            if ((qr.Type == "U") || (qr.Type == "C"))
            {
                typeResult = true;
            }
            if (int.TryParse(qr.Id, out int n))
            {
                idResult = true;
            }

            return typeResult && idResult;

        }
        public ActionResult Details()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetQRRegistrationPartial(QRViewModel qr)
        {
            UnitOfWork unitOfWork = new UnitOfWork(db);

            if (qr.Type == "U")
            {
                int uid = Convert.ToInt32(qr.Id);
                IEnumerable<Registration> registrations = unitOfWork.Registrations.GetAllUserRegistrations(uid);
                return PartialView("_UserRegistrations", registrations);
            }

MotoHub/MotoHub/MotoHub/Views/EventRegistration/CreateNew.cshtml
@model MotoHub.Models.ViewModels.RegistrationViewModel

@{
    ViewBag.Title = "Registration";
}

@{List<SelectListItem> Clublist = new List<SelectListItem>();
    foreach (var club in Model.Club.ToList())
    {
        Clublist.Add(new SelectListItem
        {
            Text = club.ClubName,
            Value = club.ClubName
        });
    }}

@{List<SelectListItem> Carlist = new List<SelectListItem>();
    foreach (var car in Model.Cars.ToList())
    {
        Carlist.Add(new SelectListItem
        {
            Text = car.CarYear.ToString() + " " + Model.CarMake.Where(m => m.CarMakeID == car.CarMakeID).Select(m => m.Make).FirstOrDefault() + " " + car.CarModel,
            Value = car.CarID.ToString()
        });
    }}

@{List<SelectListItem> carClassList = new List<SelectListItem>();
    foreach (var car in Model.CarClass.ToList())
    {
        carClassList.Add(new SelectListItem
        {
            Text = car.Class,
            Value = car.Class
        });
    }}

@{List<SelectListItem> runGroups = new List<SelectListItem>();
    foreach (var group in Model.RunGroup.ToList())
    {
        runGroups.Add(new SelectListItem
        {
            Text = group.RunGroupName,
            Value = group.RunGroupCode
        });
    }}

<h2>Registration</h2>
@using (Html.BeginForm("CreateNew", "EventRegistration", new { userID = Model.UserProfile.Select(up => up.MotoHubUserID).FirstOrDefault() }, FormMethod.Post, null))
{
    @Html.AntiForgeryToken()



    <div class="form-horizontal">

        <h4><b>Self Registration for @Model.Event.Select(m => m.EventName).FirstOrDefault() </b></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label for="Event">
                <b> Event Name: </b>
            </label>

            @{var eName = Model.Event.Select(m => m.EventName).FirstOrDefault();
            }
            <div class="form-control">
                <input type="hidden" value="@eName" id="Event" name="Event" />
                @eName
            </div>
        </div>


        <div class="form-group">
            <b> First Name: </b>
            <div id="First" name="First" class="form-control">
                @Model.UserProfile.Select(m => m.FirstName).FirstOrDefault()
            </div>
        </div>

        <div class="form-group">
            <b> Last Name: </b>
            <div class="form-control">
                @Model.UserProfile.Select(m => m.LastName).FirstOrDefault()
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Club, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.DropDownListFor(model => model.Club, Clublist, "-- Select A Club --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Club, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cars, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.DropDownListFor(model => model.Cars, Carlist, "-- Select A Car --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cars, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarClass, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.DropDownListFor(model => model.CarClass, carClassList, "-- Select A Running Class --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CarClass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RunGroup, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.DropDownListFor(model => model.RunGroup, runGroups, "-- Select A Time To Run --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RunGroup, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b>Paid:</b>
            <div col-md-10">
                <input type="checkbox" class="btn btn-default" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MotoHub/MotoHub/MotoHub/Views/EventRegistration/Details.cshtml
@section scripts
    {
        <script src="~/Scripts/qr-capture.js"></script>
        <script src="https://rawgit.com/sitepoint-editors/jsqrcode/master/src/qr_packed.js"></script>
        <script type="text/javascript">
            route = "/EventRegistration/GetQRRegistrationPartial/"
        </script>
    }
@Html.Partial("_QRCodeScan")

MotoHub/MotoHub/MotoHub/Views/EventRegistration/QRCodeScan.cshtml
@{
    ViewBag.Title = "QRCodeRegister";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts{
    <script src="~/Scripts/qr-capture.js"></script>
    <script src="https://rawgit.com/sitepoint-editors/jsqrcode/master/src/qr_packed.js">
    </script>
    <script type="text/javascript">
        route = "/EventRegistration/GetQRPartial/";
    </script>
}
<h2>QRCodeRegister</h2>
<label class="qrcode-text-btn"><input type=file class="btn" accept="image/*" capture="environment" onchange="openQRCamera(this);" id="qrcode"></label>
<div id="output"></div>